version: '3.6'
name: graphql-articles
volumes:
  db_data:
services:
  postgres:
    image: postgres:latest
    # restart: always
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: articles
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB']
      interval: 10s
      timeout: 5s
      retries: 5
  main:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
