package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/acelot/articles/internal/gql/model"
	"github.com/acelot/articles/internal/gql/runtime"
)

// ArticleBlock is the resolver for the articleBlock field.
func (r *mutationResolver) ArticleBlock(ctx context.Context) (*model.ArticleBlockMutation, error) {
	return &model.ArticleBlockMutation{}, nil
}

// ArticleBlockMutation returns runtime.ArticleBlockMutationResolver implementation.
func (r *Resolver) ArticleBlockMutation() runtime.ArticleBlockMutationResolver {
	return &articleBlockMutationResolver{r}
}

type articleBlockMutationResolver struct{ *Resolver }
