package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/acelot/articles/internal/gql/model"
	"github.com/acelot/articles/internal/gql/runtime"
)

// Image is the resolver for the image field.
func (r *queryResolver) Image(ctx context.Context) (*model.ImageQuery, error) {
	return &model.ImageQuery{}, nil
}

// ImageQuery returns runtime.ImageQueryResolver implementation.
func (r *Resolver) ImageQuery() runtime.ImageQueryResolver { return &imageQueryResolver{r} }

type imageQueryResolver struct{ *Resolver }
