package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/acelot/articles/internal/gql/model"
	"github.com/acelot/articles/internal/gql/runtime"
)

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context) (*model.ProjectQuery, error) {
	return &model.ProjectQuery{}, nil
}

// ProjectQuery returns runtime.ProjectQueryResolver implementation.
func (r *Resolver) ProjectQuery() runtime.ProjectQueryResolver { return &projectQueryResolver{r} }

type projectQueryResolver struct{ *Resolver }
