package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/acelot/articles/internal/gql/model"
	"github.com/acelot/articles/internal/gql/runtime"
)

// Project is the resolver for the project field.
func (r *mutationResolver) Project(ctx context.Context) (*model.ProjectMutation, error) {
	return &model.ProjectMutation{}, nil
}

// ProjectMutation returns runtime.ProjectMutationResolver implementation.
func (r *Resolver) ProjectMutation() runtime.ProjectMutationResolver {
	return &projectMutationResolver{r}
}

type projectMutationResolver struct{ *Resolver }
