package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/acelot/articles/internal/gql/model"
	"github.com/acelot/articles/internal/gql/runtime"
)

// Tag is the resolver for the tag field.
func (r *mutationResolver) Tag(ctx context.Context) (*model.TagMutation, error) {
	return &model.TagMutation{}, nil
}

// TagMutation returns runtime.TagMutationResolver implementation.
func (r *Resolver) TagMutation() runtime.TagMutationResolver { return &tagMutationResolver{r} }

type tagMutationResolver struct{ *Resolver }
